### ISSUE TITLE
ブランディングの変更 (Firefox ブランド削除)

### ISSUE THREAD

**Issue by dynamis** [webdino/amethyst#26]
Mozilla Firefox ブランドではなくすパッチを用意する。既に以前クリアコードで開発したもの (WIP かもしれない) を Renesas さんが持っているのでその中身を確認、必要に応じて変更を行ったものを用意してレシピに投入する。

- [x] 現状のブランディング変更パッチを受け取る
- [x] パッチを meta-browser レシピの中に入れる
- [ ] 現状のブランディング変更パッチを確認し、必要に応じて更新する
  - パッチではなくシェルスクリプトだったがいずれにしても確認して更新する
  - [ ] バイナリ名やパスから firefox を削除して仮に webviewer に
  - [ ] ローカライズの branding ファイルでの名称を変更
     - Mozilla Firefox/Nightly -> WebViewer
     - Firefox/Nightly -> WebViewer
  - [x] Firefox のロゴを含んでいる画像ファイルを差し換え (ビルド結果に含まれてしまう場合)
     - Nightly ロゴはそのままでも良い？ルネサスカラーの地球ロゴなどを作る？
  - [ ] その他ハードコーディングされてしまっている箇所を確認
      - スクリプトで一括置き返されてるからなさそうだが、スクリプト実行後のコードを確認
- [x] リリース用のブランドに変更する準備
  - [x] ビルド名を何にするか確認・確定させる - WebViewer で良いと確認した
  - [x] 差し換え実行

**Comment by YoshihiroOota** [comment]
一応、弊社で確認できた箇所にチェックを入れてみました。
Gecko 60 向け Web Viewer は公開されておりますし、ブランディング変更の作業は完了できたと思いますが、Close 可能かご確認いただけないでしょうか。
Gecko 68 向けは、#43 辺りにまとめるか、別 issue を立てるのが分かりやすいと思います。

**Comment by dynamis** [comment]
遅くなりましたが、完了していると思いますのでクローズします (必要があれば個別に issue 立てましょう)
